// Sidebar
export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY';

// Modals
export const SET_IMPORT_PROJECT_MODAL_VISIBILITY =
  'SET_IMPORT_PROJECT_MODAL_VISIBILITY';
export const SET_CREATE_PROJECT_MODAL_VISIBILITY =
  'SET_CREATE_PROJECT_MODAL_VISIBILITY';
